using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace App.Application.Handlers.currencyConverter
{
    public class CurrencyEnum
    {
        public enum Currency
        {
            SAR = 1,
            EGP,
            USD,
            AMD,
            ANG,
            AOA,
            ARS,
            AUD,
            AWG,
            AZN,
            BAM,
            BBD,
            BDT,
            BGN,
            BHD,
            BIF,
            BMD,
            BND,
            BOB,
            BRL,
            BSD,
            BTC,
            BTN,
            BWP,
            BYN,
            BZD,
            CAD,
            CDF,
            CHF,
            CLF,
            CLP,
            CNH,
            CNY,
            COP,
            CRC,
            CUC,
            CUP,
            CVE,
            CZK,
            DJF,
            DKK,
            DOP,
            DZD,
            AFN,
            ERN,
            ETB,
            EUR,
            FJD,
            FKP,
            GBP,
            GEL,
            GGP,
            GHS,
            GIP,
            GMD,
            GNF,
            GTQ,
            GYD,
            HKD,
            HNL,
            HRK,
            HTG,
            HUF,
            IDR,
            ILS,
            IMP,
            INR,
            IQD,
            IRR,
            ISK,
            JEP,
            JMD,
            JOD,
            JPY,
            KES,
            KGS,
            KHR,
            KMF,
            KPW,
            KRW,
            KWD,
            KYD,
            KZT,
            LAK,
            LBP,
            LKR,
            LRD,
            LSL,
            LYD,
            MAD,
            MDL,
            MGA,
            MKD,
            MMK,
            MNT,
            MOP,
            MRU,
            MUR,
            MVR,
            MWK,
            MXN,
            MYR,
            MZN,
            NAD,
            NGN,
            NIO,
            NOK,
            NPR,
            NZD,
            OMR,
            PAB,
            PEN,
            PGK,
            PHP,
            PKR,
            PLN,
            PYG,
            QAR,
            RON,
            RSD,
            RUB,
            RWF,
            AED,
            SBD,
            SCR,
            SDG,
            SEK,
            SGD,
            SHP,
            SLL,
            SOS,
            SRD,
            SSP,
            STD,
            STN,
            SVC,
            SYP,
            SZL,
            THB,
            TJS,
            TMT,
            TND,
            TOP,
            TRY,
            TTD,
            TWD,
            TZS,
            UAH,
            UGX,
            ALL,
            UYU,
            UZS,
            VEF,
            VES,
            VND,
            VUV,
            WST,
            XAF,
            XAG,
            XAU,
            XCD,
            XDR,
            XOF,
            XPD,
            XPF,
            XPT,
            YER,
            ZAR,
            ZMW,
            ZWL
        }
        public static List<CurrencyDTO> CurrenciesList = new List<CurrencyDTO>
        {
            new CurrencyDTO{Id = (int)Currency.SAR,arabicName = "الريال السعودي",latinName =   "Saudi Riyal"},
            new CurrencyDTO{Id = (int)Currency.EGP,arabicName = "الجنيه المصري",latinName =   "Egyptian Pound"},
            new CurrencyDTO{Id = (int)Currency.USD,arabicName = "دولار الولايات المتحدة",latinName =   "United States Dollar"},
            new CurrencyDTO{Id = (int)Currency.AED,arabicName = "درهم الإمارات العربية المتحدة",latinName =   "United Arab Emirates Dirham"},
            new CurrencyDTO{Id = (int)Currency.AFN,arabicName = "أفغاني أفغاني",latinName =   "Afghan Afghani"},
            new CurrencyDTO{Id = (int)Currency.ALL,arabicName = "ليك الألباني",latinName =   "Albanian Lek"},
            new CurrencyDTO{Id = (int)Currency.AMD,arabicName = "الطبل الأرمني",latinName =   "Armenian Dram"},
            new CurrencyDTO{Id = (int)Currency.ANG,arabicName = "غيلدر جزر الأنتيل الهولندية",latinName =   "Netherlands Antillean Guilder"},
            new CurrencyDTO{Id = (int)Currency.AOA,arabicName = "الكوانزا الأنغولية",latinName =   "Angolan Kwanza"},
            new CurrencyDTO{Id = (int)Currency.ARS,arabicName = "البيزو الأرجنتيني",latinName =   "Argentine Peso"},
            new CurrencyDTO{Id = (int)Currency.AUD,arabicName = "دولار استرالي",latinName =   "Australian Dollar"},
            new CurrencyDTO{Id = (int)Currency.AWG,arabicName = "الفلورين الأروبي",latinName =   "Aruban Florin"},
            new CurrencyDTO{Id = (int)Currency.AZN,arabicName = "مانات أذربيجاني",latinName =   "Azerbaijani Manat"},
            new CurrencyDTO{Id = (int)Currency.BAM,arabicName = "مارك البوسنة والهرسك القابل للتحويل",latinName =   "Bosnia-Herzegovina Convertible Mark"},
            new CurrencyDTO{Id = (int)Currency.BBD,arabicName = "الدولار البربادوسي",latinName =   "Barbadian Dollar"},
            new CurrencyDTO{Id = (int)Currency.BDT,arabicName = "التاكا البنجلاديشية",latinName =   "Bangladeshi Taka"},
            new CurrencyDTO{Id = (int)Currency.BGN,arabicName = "ليف البلغاري",latinName =   "Bulgarian Lev"},
            new CurrencyDTO{Id = (int)Currency.BHD,arabicName = "دينار بحريني",latinName =   "Bahraini Dinar"},
            new CurrencyDTO{Id = (int)Currency.BIF,arabicName = "الفرنك البوروندي",latinName =   "Burundian Franc"},
            new CurrencyDTO{Id = (int)Currency.BMD,arabicName = "الدولار البرمودي",latinName =   "Bermudan Dollar"},
            new CurrencyDTO{Id = (int)Currency.BND,arabicName = "الدولار البروناي",latinName =   "Brunei Dollar"},
            new CurrencyDTO{Id = (int)Currency.BOB,arabicName = "بوليفيانو البوليفي",latinName =   "Bolivian Boliviano"},
            new CurrencyDTO{Id = (int)Currency.BRL,arabicName = "ريال برازيلي",latinName =   "Brazilian Real"},
            new CurrencyDTO{Id = (int)Currency.BSD,arabicName = "الدولار البهامي",latinName =   "Bahamian Dollar"},
            new CurrencyDTO{Id = (int)Currency.BTC,arabicName = "بيتكوين",latinName =   "Bitcoin"},
            new CurrencyDTO{Id = (int)Currency.BTN,arabicName = "نغولتروم بوتان",latinName =   "Bhutanese Ngultrum"},
            new CurrencyDTO{Id = (int)Currency.BWP,arabicName = "بوتسوانا بولا",latinName =   "Botswanan Pula"},
            new CurrencyDTO{Id = (int)Currency.BYN,arabicName = "الروبل البيلاروسي",latinName =   "Belarusian Ruble"},
            new CurrencyDTO{Id = (int)Currency.BZD,arabicName = "دولار بليز",latinName =   "Belize Dollar"},
            new CurrencyDTO{Id = (int)Currency.CAD,arabicName = "الدولار الكندي",latinName =   "Canadian Dollar"},
            new CurrencyDTO{Id = (int)Currency.CDF,arabicName = "الفرنك الكونغولي",latinName =   "Congolese Franc"},
            new CurrencyDTO{Id = (int)Currency.CHF,arabicName = "الفرنك السويسري",latinName =   "Swiss Franc"},
            new CurrencyDTO{Id = (int)Currency.CLF,arabicName = "وحدة الحساب التشيلية (UF)",latinName =   "Chilean Unit of Account (UF)"},
            new CurrencyDTO{Id = (int)Currency.CLP,arabicName = "البيزو التشيلي",latinName =   "Chilean Peso"},
            new CurrencyDTO{Id = (int)Currency.CNH,arabicName = "اليوان الصيني (في الخارج)",latinName =   "Chinese Yuan (Offshore)"},
            new CurrencyDTO{Id = (int)Currency.CNY,arabicName = "اليوان الصيني",latinName =   "Chinese Yuan"},
            new CurrencyDTO{Id = (int)Currency.COP,arabicName = "البيزو الكولومبي",latinName =   "Colombian Peso"},
            new CurrencyDTO{Id = (int)Currency.CRC,arabicName = "الكولون الكوستاريكي",latinName =   "Costa Rican Colón"},
            new CurrencyDTO{Id = (int)Currency.CUC,arabicName = "البيزو الكوبي القابل للتحويل",latinName =   "Cuban Convertible Peso"},
            new CurrencyDTO{Id = (int)Currency.CUP,arabicName = "البيزو الكوبي",latinName =   "Cuban Peso"},
            new CurrencyDTO{Id = (int)Currency.CVE,arabicName = "إسكودو الرأس الأخضر",latinName =   "Cape Verdean Escudo"},
            new CurrencyDTO{Id = (int)Currency.CZK,arabicName = "كورونا جمهورية التشيك",latinName =   "Czech Republic Koruna"},
            new CurrencyDTO{Id = (int)Currency.DJF,arabicName = "الفرنك الجيبوتي",latinName =   "Djiboutian Franc"},
            new CurrencyDTO{Id = (int)Currency.DKK,arabicName = "الكرونة الدنماركية",latinName =   "Danish Krone"},
            new CurrencyDTO{Id = (int)Currency.DOP,arabicName = "البيزو الدومينيكي",latinName =   "Dominican Peso"},
            new CurrencyDTO{Id = (int)Currency.DZD,arabicName = "الدينار الجزائري",latinName =   "Algerian Dinar"},
            new CurrencyDTO{Id = (int)Currency.ERN,arabicName = "النكفا الإريترية",latinName =   "Eritrean Nakfa"},
            new CurrencyDTO{Id = (int)Currency.ETB,arabicName = "البير الإثيوبي",latinName =   "Ethiopian Birr"},
            new CurrencyDTO{Id = (int)Currency.EUR,arabicName = "اليورو",latinName =   "Euro"},
            new CurrencyDTO{Id = (int)Currency.FJD,arabicName = "الدولار الفيجي",latinName =   "Fijian Dollar"},
            new CurrencyDTO{Id = (int)Currency.FKP,arabicName = "جنيه جزر فوكلاند",latinName =   "Falkland Islands Pound"},
            new CurrencyDTO{Id = (int)Currency.GBP,arabicName = "الجنيه الاسترليني",latinName =   "British Pound Sterling"},
            new CurrencyDTO{Id = (int)Currency.GEL,arabicName = "الجورجي لاري",latinName =   "Georgian Lari"},
            new CurrencyDTO{Id = (int)Currency.GGP,arabicName = "الجنيه الجيرنسي",latinName =   "Guernsey Pound"},
            new CurrencyDTO{Id = (int)Currency.GHS,arabicName = "سيدي الغاني",latinName =   "Ghanaian Cedi"},
            new CurrencyDTO{Id = (int)Currency.GIP,arabicName = "جنيه جبل طارق",latinName =   "Gibraltar Pound"},
            new CurrencyDTO{Id = (int)Currency.GMD,arabicName = "دالاسي الغامبية",latinName =   "Gambian Dalasi"},
            new CurrencyDTO{Id = (int)Currency.GNF,arabicName = "الفرنسية الغينية",latinName =   "Guinean Franc"},
            new CurrencyDTO{Id = (int)Currency.GTQ,arabicName = "الكوازال الغواتيمالي",latinName =   "Guatemalan Quetzal"},
            new CurrencyDTO{Id = (int)Currency.GYD,arabicName = "الدولار الغياني",latinName =   "Guyanaese Dollar"},
            new CurrencyDTO{Id = (int)Currency.HKD,arabicName = "الدولار هونج كونج",latinName =   "Hong Kong Dollar"},
            new CurrencyDTO{Id = (int)Currency.HNL,arabicName = "ليمبيرا هندوراس",latinName =   "Honduran Lempira"},
            new CurrencyDTO{Id = (int)Currency.HRK,arabicName = "كونا كرواتية",latinName =   "Croatian Kuna"},
            new CurrencyDTO{Id = (int)Currency.HTG,arabicName = "الجورد الهايتي",latinName =   "Haitian Gourde"},
            new CurrencyDTO{Id = (int)Currency.HUF,arabicName = "الفورنت المجري",latinName =   "Hungarian Forint"},
            new CurrencyDTO{Id = (int)Currency.IDR,arabicName = "الروبية الإندونيسية",latinName =   "Indonesian Rupiah"},
            new CurrencyDTO{Id = (int)Currency.ILS,arabicName = "الشيكل الإسرائيلي الجديد",latinName =   "Israeli New Sheqel"},
            new CurrencyDTO{Id = (int)Currency.IMP,arabicName = "جنيه مانكس",latinName =   "Manx pound"},
            new CurrencyDTO{Id = (int)Currency.INR,arabicName = "الروبية الهندية",latinName =   "Indian Rupee"},
            new CurrencyDTO{Id = (int)Currency.IQD,arabicName = "الدينار العراقي",latinName =   "Iraqi Dinar"},
            new CurrencyDTO{Id = (int)Currency.IRR,arabicName = "الريال الإيراني",latinName =   "Iranian Rial"},
            new CurrencyDTO{Id = (int)Currency.ISK,arabicName = "الكرونة الأيسلندية",latinName =   "Icelandic Króna"},
            new CurrencyDTO{Id = (int)Currency.JEP,arabicName = "الجنيه الجيرسي",latinName =   "Jersey Pound"},
            new CurrencyDTO{Id = (int)Currency.JMD,arabicName = "الدولار الجامايكي",latinName =   "Jamaican Dollar"},
            new CurrencyDTO{Id = (int)Currency.JOD,arabicName = "الدينار الأردني",latinName =   "Jordanian Dinar"},
            new CurrencyDTO{Id = (int)Currency.JPY,arabicName = "الين الياباني",latinName =   "Japanese Yen"},
            new CurrencyDTO{Id = (int)Currency.KES,arabicName = "الشلن الكيني",latinName =   "Kenyan Shilling"},
            new CurrencyDTO{Id = (int)Currency.KGS,arabicName = "السوم القيرغيستاني",latinName =   "Kyrgystani Som"},
            new CurrencyDTO{Id = (int)Currency.KHR,arabicName = "الريال الكمبودي",latinName =   "Cambodian Riel"},
            new CurrencyDTO{Id = (int)Currency.KMF,arabicName = "الفرنك القمري",latinName =   "Comorian Franc"},
            new CurrencyDTO{Id = (int)Currency.KPW,arabicName = "وون كوريا الشمالية",latinName =   "North Korean Won"},
            new CurrencyDTO{Id = (int)Currency.KRW,arabicName = "وون كوريا الجنوبية",latinName =   "South Korean Won"},
            new CurrencyDTO{Id = (int)Currency.KWD,arabicName = "دينار كويتي",latinName =   "Kuwaiti Dinar"},
            new CurrencyDTO{Id = (int)Currency.KYD,arabicName = "دولار جزر كايمان",latinName =   "Cayman Islands Dollar"},
            new CurrencyDTO{Id = (int)Currency.KZT,arabicName = "التنغ الكازاخستاني",latinName =   "Kazakhstani Tenge"},
            new CurrencyDTO{Id = (int)Currency.LAK,arabicName = "كيب لاوسي",latinName =   "Laotian Kip"},
            new CurrencyDTO{Id = (int)Currency.LBP,arabicName = "الليرة اللبنانية",latinName =   "Lebanese Pound"},
            new CurrencyDTO{Id = (int)Currency.LKR,arabicName = "الروبية السريلانكية",latinName =   "Sri Lankan Rupee"},
            new CurrencyDTO{Id = (int)Currency.LRD,arabicName = "الدولار الليبيري",latinName =   "Liberian Dollar"},
            new CurrencyDTO{Id = (int)Currency.LSL,arabicName = "لوتي ليسوتو",latinName =   "Lesotho Loti"},
            new CurrencyDTO{Id = (int)Currency.LYD,arabicName = "الدينار الليبي",latinName =   "Libyan Dinar"},
            new CurrencyDTO{Id = (int)Currency.MAD,arabicName = "الدرهم المغربي",latinName =   "Moroccan Dirham"},
            new CurrencyDTO{Id = (int)Currency.MDL,arabicName = "ليو مولدوفا",latinName =   "Moldovan Leu"},
            new CurrencyDTO{Id = (int)Currency.MGA,arabicName = "أرياري مدغشقر",latinName =   "Malagasy Ariary"},
            new CurrencyDTO{Id = (int)Currency.MKD,arabicName = "الدينار المقدوني",latinName =   "Macedonian Denar"},
            new CurrencyDTO{Id = (int)Currency.MMK,arabicName = "ميانما كيات",latinName =   "Myanma Kyat"},
            new CurrencyDTO{Id = (int)Currency.MNT,arabicName = "التوغريك المنغولي",latinName =   "Mongolian Tugrik"},
            new CurrencyDTO{Id = (int)Currency.MOP,arabicName = "باتاكا ماكاوية",latinName =   "Macanese Pataca"},
            new CurrencyDTO{Id = (int)Currency.MRU,arabicName = "الأوقية الموريتانية",latinName =   "Mauritanian Ouguiya"},
            new CurrencyDTO{Id = (int)Currency.MUR,arabicName = "روبية موريشيوسية",latinName =   "Mauritian Rupee"},
            new CurrencyDTO{Id = (int)Currency.MVR,arabicName = "الروفية المالديفية",latinName =   "Maldivian Rufiyaa"},
            new CurrencyDTO{Id = (int)Currency.MWK,arabicName = "الكواشا الملاوية",latinName =   "Malawian Kwacha"},
            new CurrencyDTO{Id = (int)Currency.MXN,arabicName = "البيزو المكسيكي",latinName =   "Mexican Peso"},
            new CurrencyDTO{Id = (int)Currency.MYR,arabicName = "رينغيت ماليزي",latinName =   "Malaysian Ringgit"},
            new CurrencyDTO{Id = (int)Currency.MZN,arabicName = "الميتيكال الموزمبيقي",latinName =   "Mozambican Metical"},
            new CurrencyDTO{Id = (int)Currency.NAD,arabicName = "الدولار الناميبي",latinName =   "Namibian Dollar"},
            new CurrencyDTO{Id = (int)Currency.NGN,arabicName = "نايرا نيجيرية",latinName =   "Nigerian Naira"},
            new CurrencyDTO{Id = (int)Currency.NIO,arabicName = "قرطبة نيكاراجوا",latinName =   "Nicaraguan Córdoba"},
            new CurrencyDTO{Id = (int)Currency.NOK,arabicName = "الكرونة النرويجية",latinName =   "Norwegian Krone"},
            new CurrencyDTO{Id = (int)Currency.NPR,arabicName = "الروبية النيبالية",latinName =   "Nepalese Rupee"},
            new CurrencyDTO{Id = (int)Currency.NZD,arabicName = "الدولار النيوزيلندي",latinName =   "New Zealand Dollar"},
            new CurrencyDTO{Id = (int)Currency.OMR,arabicName = "الريال العماني",latinName =   "Omani Rial"},
            new CurrencyDTO{Id = (int)Currency.PAB,arabicName = "البالبوا البنمي",latinName =   "Panamanian Balboa"},
            new CurrencyDTO{Id = (int)Currency.PEN,arabicName = "نويفو سول البيروية",latinName =   "Peruvian Nuevo Sol"},
            new CurrencyDTO{Id = (int)Currency.PGK,arabicName = "بابوا غينيا الجديدة كينا",latinName =   "Papua New Guinean Kina"},
            new CurrencyDTO{Id = (int)Currency.PHP,arabicName = "البيزو الفلبيني",latinName =   "Philippine Peso"},
            new CurrencyDTO{Id = (int)Currency.PKR,arabicName = "الروبية الباكستانية",latinName =   "Pakistani Rupee"},
            new CurrencyDTO{Id = (int)Currency.PLN,arabicName = "الزلوتي البولندي",latinName =   "Polish Zloty"},
            new CurrencyDTO{Id = (int)Currency.PYG,arabicName = "الغواراني الباراجواياني",latinName =   "Paraguayan Guarani"},
            new CurrencyDTO{Id = (int)Currency.QAR,arabicName = "الريال القطري",latinName =   "Qatari Rial"},
            new CurrencyDTO{Id = (int)Currency.RON,arabicName = "الأسد الروماني",latinName =   "Romanian Leu"},
            new CurrencyDTO{Id = (int)Currency.RSD,arabicName = "الدينار الصربي",latinName =   "Serbian Dinar"},
            new CurrencyDTO{Id = (int)Currency.RUB,arabicName = "الروبل الروسي",latinName =   "Russian Ruble"},
            new CurrencyDTO{Id = (int)Currency.RWF,arabicName = "الفرنك الرواندي",latinName =   "Rwandan Franc"},
            new CurrencyDTO{Id = (int)Currency.SBD,arabicName = "دولار جزر سليمان",latinName =   "Solomon Islands Dollar"},
            new CurrencyDTO{Id = (int)Currency.SCR,arabicName = "الروبية السيشيلية",latinName =   "Seychellois Rupee"},
            new CurrencyDTO{Id = (int)Currency.SDG,arabicName = "الجنيه السوداني",latinName =   "Sudanese Pound"},
            new CurrencyDTO{Id = (int)Currency.SEK,arabicName = "كرونة سويدية",latinName =   "Swedish Krona"},
            new CurrencyDTO{Id = (int)Currency.SGD,arabicName = "دولار سينغافوري",latinName =   "Singapore Dollar"},
            new CurrencyDTO{Id = (int)Currency.SHP,arabicName = "جنيه سانت هيلينا",latinName =   "Saint Helena Pound"},
            new CurrencyDTO{Id = (int)Currency.SLL,arabicName = "الليون السيراليوني",latinName =   "Sierra Leonean Leone"},
            new CurrencyDTO{Id = (int)Currency.SOS,arabicName = "الشلن الصومالي",latinName =   "Somali Shilling"},
            new CurrencyDTO{Id = (int)Currency.SRD,arabicName = "الدولار السورينامي",latinName =   "Surinamese Dollar"},
            new CurrencyDTO{Id = (int)Currency.SSP,arabicName = "جنيه جنوب السودان",latinName =   "South Sudanese Pound"},
            new CurrencyDTO{Id = (int)Currency.STD,arabicName = "ساو تومي وبرينسيبي دوبرا (قبل 2018)",latinName =   "São Tomé and Príncipe Dobra (pre-2018)"},
            new CurrencyDTO{Id = (int)Currency.STN,arabicName = "ساو تومي وبرينسيبي دوبرا",latinName =   "São Tomé and Príncipe Dobra"},
            new CurrencyDTO{Id = (int)Currency.SVC,arabicName = "القولون السلفادوري",latinName =   "Salvadoran Colón"},
            new CurrencyDTO{Id = (int)Currency.SYP,arabicName = "الليرة السورية",latinName =   "Syrian Pound"},
            new CurrencyDTO{Id = (int)Currency.SZL,arabicName = "ليلانجيني السوازي",latinName =   "Swazi Lilangeni"},
            new CurrencyDTO{Id = (int)Currency.THB,arabicName = "البات التايلندي",latinName =   "Thai Baht"},
            new CurrencyDTO{Id = (int)Currency.TJS,arabicName = "السوموني الطاجيكي",latinName =   "Tajikistani Somoni"},
            new CurrencyDTO{Id = (int)Currency.TMT,arabicName = "مانات تركمانستان",latinName =   "Turkmenistani Manat"},
            new CurrencyDTO{Id = (int)Currency.TND,arabicName = "الدينار التونسي",latinName =   "Tunisian Dinar"},
            new CurrencyDTO{Id = (int)Currency.TOP,arabicName = "تونغا بانجا",latinName =   "Tongan Pa'anga"},
            new CurrencyDTO{Id = (int)Currency.TRY,arabicName = "الليرة التركية",latinName =   "Turkish Lira"},
            new CurrencyDTO{Id = (int)Currency.TTD,arabicName = "دولار ترينيداد وتوباغو",latinName =   "Trinidad and Tobago Dollar"},
            new CurrencyDTO{Id = (int)Currency.TWD,arabicName = "دولار تايوان الجديد",latinName =   "New Taiwan Dollar"},
            new CurrencyDTO{Id = (int)Currency.TZS,arabicName = "الشلن التنزاني",latinName =   "Tanzanian Shilling"},
            new CurrencyDTO{Id = (int)Currency.UAH,arabicName = "الهريفنيا الأوكرانية",latinName =   "Ukrainian Hryvnia"},
            new CurrencyDTO{Id = (int)Currency.UGX,arabicName = "الشلن الأوغندي",latinName =   "Ugandan Shilling"},
            new CurrencyDTO{Id = (int)Currency.UYU,arabicName = "البيزو الأوروغوياني",latinName =   "Uruguayan Peso"},
            new CurrencyDTO{Id = (int)Currency.UZS,arabicName = "السوم الأوزبكي",latinName =   "Uzbekistan Som"},
            new CurrencyDTO{Id = (int)Currency.VEF,arabicName = "فنزويلا بوليفار فويرتي (قديم)",latinName =   "Venezuelan Bolívar Fuerte (Old)"},
            new CurrencyDTO{Id = (int)Currency.VES,arabicName = "فنزويلا بوليفار سوبيرانو",latinName =   "Venezuelan Bolívar Soberano"},
            new CurrencyDTO{Id = (int)Currency.VND,arabicName = "الدونغ الفيتنامي",latinName =   "Vietnamese Dong"},
            new CurrencyDTO{Id = (int)Currency.VUV,arabicName = "فاتو فانواتو",latinName =   "Vanuatu Vatu"},
            new CurrencyDTO{Id = (int)Currency.WST,arabicName = "ساموان تالا",latinName =   "Samoan Tala"},
            new CurrencyDTO{Id = (int)Currency.XAF,arabicName = "فرنك CFA",latinName =   "CFA Franc BEAC"},
            new CurrencyDTO{Id = (int)Currency.XAG,arabicName = "أوقية الفضة",latinName =   "Silver Ounce"},
            new CurrencyDTO{Id = (int)Currency.XAU,arabicName = "أونصة الذهب",latinName =   "Gold Ounce"},
            new CurrencyDTO{Id = (int)Currency.XCD,arabicName = "دولار شرق الكاريبي",latinName =   "East Caribbean Dollar"},
            new CurrencyDTO{Id = (int)Currency.XDR,arabicName = "حقوق السحب الخاصة",latinName =   "Special Drawing Rights"},
            new CurrencyDTO{Id = (int)Currency.XOF,arabicName = "فرنك CFA BCEAO",latinName =   "CFA Franc BCEAO"},
            new CurrencyDTO{Id = (int)Currency.XPD,arabicName = "أونصة البلاديوم",latinName =   "Palladium Ounce"},
            new CurrencyDTO{Id = (int)Currency.XPF,arabicName = "فرنك سي إف بي",latinName =   "CFP Franc"},
            new CurrencyDTO{Id = (int)Currency.XPT,arabicName = "أوقية البلاتين",latinName =   "Platinum Ounce"},
            new CurrencyDTO{Id = (int)Currency.YER,arabicName = "الريال اليمني",latinName =   "Yemeni Rial"},
            new CurrencyDTO{Id = (int)Currency.ZAR,arabicName = "راند جنوب أفريقيا",latinName =   "South African Rand"},
            new CurrencyDTO{Id = (int)Currency.ZMW,arabicName = "الكواشا الزامبية",latinName =   "Zambian Kwacha"},
            new CurrencyDTO{Id = (int)Currency.ZWL,arabicName = "الدولار الزيمبابوي",latinName =   "Zimbabwean Dollar"},
        };
    }

    public class CurrencyDTO
    {
        public int Id { get; set; }
        public string arabicName { get; set; }
        public string latinName { get; set; }
    }
}
